### ISSUE TITLE
Users didn't read 'about the service'

### ISSUE THREAD

**Issue by joanneSouthern** [alphagov/verify-local-patterns#360]

**Comment by EUzkuraityte** [comment]
Bucks found that: 

Users do not read below the 'Apply' button on this page: https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/resident-start

**Comment by lizziebruce** [comment]
Same issue addressed in #397 (despite different service)

**Comment by lizziebruce** [comment]
Some changes made to copy for this page to make it more concise and therefore more engaging – but may need to move key info above the Apply button. As the copy is now more concise it wouldn't have to mean the Apply button is pushed too far down the page. 

https://docs.google.com/document/d/1b9rLsp0rQF199U4JLsZtNezuQR9kCI_U-hkHl6E3N6w/edit#heading=h.r96wk8rljsr7

**Comment by EUzkuraityte** [comment]
evidence from Oxfordshire:
Impact: Users may miss the information telling them what they will need in order to make the application.
Evidence: “Wouldn’t read the rest, I already know what I want. Might just scan it.”
“Unlikely to read the rest of is, would probably just click to apply.”
Users said later in the application that they wish they’d been told what they would need in advance of starting the application.
“No warning of needing documents before this point.”

**Comment by lizziebruce** [comment]
Related to #313 - this page now has a What you'll need section above the Apply button. However, there is also more copy on the page due to the Costs section. Note that the Costs section will commonly be shorter as it currently shows some local variation.

Revised page content:

<img width="537" alt="screen shot 2017-05-10 at 18 05 47" src="https://cloud.githubusercontent.com/assets/27814324/25956746/76e99ca2-3664-11e7-91a4-46251a05bc90.png">

**Comment by EUzkuraityte** [comment]
@lizziebruce sounds good, I've dragged this issue into ;Recent changes could affect this. Are we still seeing this need in research?' so we can close this after Monday sessions

**Comment by petegale** [comment]
Round 3:
![screen shot 2017-05-22 at 11 24 52](https://cloud.githubusercontent.com/assets/2970019/26303930/530554e0-3ee1-11e7-954f-765a56053e2d.png)
